# recipe = Recipe.create(name: "buffalo chicken dip", image: "https://cafedelites.com/wp-content/uploads/2019/12/Buffalo-Chicken-Dip-RECIPE-IMAGE-88-200x200.jpg", description: "Buffalo chicken dip is sinfully creamy and mouthwatering comfort food. Hot wing flavours infused into a delicious dip perfect to serve as an appetizer for any special occasion!",ingredients: "1 tablespoon unsalted butter 2 teaspoons minced garlic 2 cups cooked chicken shredded 1/2 cup Frank's Original Red Hot Sauce 8 oz (250g) g block cream cheese, softened 1/2 cup sour cream 1/2 cup white Cheddar cheese freshly shredded 1/4 cup American cheddar freshly shredded 1/4 cup crumbled blue cheese (optional to serve) 2 teaspoons green onions, sliced ( or chives) Celery sticks carrot sticks, tortilla chips, crusty bread pieces, potato chips, for serving", instructions: "Preheat oven to 375°F (190°C). Arrange oven rack to the middle of your oven.
# In an 8-inch cast-iron skillet (or an ovenproof pan), melt the butter over medium-high heat. Sauté garlic until fragrant (30 seconds). Add the chicken and hot sauce and simmer until sauce has thickened and reduced by half (about 2 minutes). Reduce heat to low and stir in cream cheese; mix until combined. Take off heat, stir through sour cream and top with both cheddar cheese(s) over the top. Bake until bubbling around the edges and the cheese has melted (about 10 minutes). Broil (or grill) for a further minute to brown on top. Immediately garnish with blue cheese and green onions. Serve with vegetable sticks, chips, crusty bread pieces for dipping.")

# recipe = Recipe.create(name: "chicken alfredo", image: "https://bellyfull.net/wp-content/uploads/2021/02/Chicken-Alfredo-blog-3-150x150.jpg", description: "This easy Chicken Alfredo recipe includes golden pan-fried chicken breasts and tender noodles, coated in the most dreamy cream sauce ever!",ingredients: "For the Chicken 1 pound boneless, skinless chicken breasts 1 teaspoon Italian seasoning 3/4 teaspoon kosher salt 1/4 teaspoon pepper 2 tablespoons extra-virgin olive oil 1 tablespoon butter For the Sauce 1/2 cup butter , cut into large cubes or slices 2 cups heavy whipping cream 1 clove garlic , minced 3/4 teaspoon garlic powder 3/4 teaspoon Italian Seasoning 1/4 teaspoon salt 1/4 teaspoon pepper 2 cups freshly grated Parmesan cheese", instructions: "Make the noodles: Bring a large pot of salted water to a boil. Add the fettuccine and cook until al dente according to package directions, usually 10 minutes. Reserve 1/2 cup of the cooking water, then drain well. Set aside.
# Make the chicken: Season chicken breasts with the Italian seasoning, salt, and pepper.
# Warm the olive oil over medium-high heat in a large nonstick skillet. Once it’s shimmering, swirl the pan to evenly distribute. Add the chicken and leave it undisturbed for 5-7 minutes, until the bottom is golden-brown. Flip over and add in 1 tablespoon of butter between them, picking up the pan to give it a gentle swirl to distribute. Continue cooking for another 5-7 minutes (or an internal temperature reaches 165 degrees F.)
# Transfer the chicken to a cutting board and let rest for 3 minutes. Cut into 1/2-inch-thick slices. Tent with foil while you prepare the sauce.
# Make the Alfredo sauce: In the same pan, over medium-low heat, add the butter and cream; whisk until butter has melted.
# Add in the minced garlic, garlic powder, Italian seasoning, salt, and pepper; whisk until combined and smooth.
# Bring to a gentle simmer (do not boil) and cook for 3-4 minutes, whisking constantly, until it starts to thicken.
# Stir in the parmesan cheese just until melted and the sauce is smooth. (If the sauce ends up too thick, add some of the reserved pasta cooking water, a few tablespoons at a time, to thin it out.)
# Assemble: Take sauce off the heat and immediately toss with the cooked fettuccine noodles.
# Divide the pasta among serving bowls and top with a few slices of chicken. Garnish with parsley, more Parmesan, and black pepper if desired.")

# recipe = Recipe.create(name: "baked mac and cheese", image: "", description: "This baked mac and cheese is a family favorite recipe, loved by children and adults.",ingredients: "1 lb. dried elbow pasta 1/2 cup unsalted butter 1/2 cup all purpose flour 1 1/2 cups whole milk 2 1/2 cups half and half 4 cups shredded medium cheddar cheese divided (measured after shredding) 2 cups shredded Gruyere cheese divided (measured after shredding) 1/2 Tbsp. salt 1/2 tsp. black pepper 1/4 tsp. paprika", instructions: "Preheat oven to 325 degrees F and grease a 3 qt baking dish (9x13\").  Set aside.
# Bring a large pot of salted water to a boil.  When boiling, add dried pasta and cook 1 minute less than the package directs for al dente.  Drain and drizzle with a little bit of olive oil to keep from sticking.
# While water is coming up to a boil, shred cheeses and toss together to mix, then divide into three piles.  Approximately 3 cups for the sauce, 1 1/2 cups for the inner layer, and 1 1/2 cups for the topping.
# Melt butter in a large saucepan over MED heat.  Sprinkle in flour and whisk to combine.  Mixture will look like very wet sand.  Cook for approximately 1 minute, whisking often.  Slowly pour in about 2 cups or so of the half and half, while whisking constantly, until smooth.  Slowly pour in the remaining half and half and the whole milk, while whisking constantly, until combined and smooth.
# Continue to heat over MED heat, whisking very often, until thickened to a very thick consistency.  It should almost be the consistency of a semi thinned out condensed soup.
# Remove from the heat and stir in spices and 1 1/2 cups of the cheeses, stirring to melt and combine.  Stir in another 1 1/2 cups of cheese, and stir until completely melted and smooth.
# In a large mixing bowl, combine drained pasta with cheese sauce, stirring to combine fully.  Pour half of the pasta mixture into the prepared baking dish.  Top with 1 1/2 cups of shredded cheeses, then top that with the remaining pasta mixture.
# Sprinkle the top with the last 1 1/2 cups of cheese and bake for 15 minutes, until cheesy is bubbly and lightly golden brown.")
